apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy  # Changed from my-app to swiggy
  labels:
    app: swiggy  # Changed from my-app to swiggy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy  # Changed from my-app to swiggy
  template:
    metadata:
      labels:
        app: swiggy  # Changed from my-app to swiggy
    spec:
      containers:
      - name: swiggy  # Changed from my-app to swiggy
        image: antosabin/swiggy:latest
        ports:
        - containerPort: 80
