apiVersion: v1
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 13.202.56.132/32
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system
