apiVersion: v1
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 3.7.157.12/32
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system
