apiVersion: v1
kind: ConfigMap
metadata:
  namespace: swiggy
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 65.1.128.249
