apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
  namespace: swiggy  # Add namespace for consistency
spec:
  type: LoadBalancer
  selector:
    app: swiggy
  ports:
  - port: 80
    targetPort: 80  # Changed from 8080 to 80
