apiVersion: v1
kind: Service
metadata:
  name: swiggy-service  # Changed from my-app-service to swiggy-service
spec:
  selector:
    app: swiggy
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
    - port: 80
      nodePort: 32414
      targetPort: 80

