apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
spec:
  selector:
    app: swiggy
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32414  
