apiVersion: v1
kind: Service
metadata:
  name: swiggy-service  # Changed from my-app-service to swiggy-service
spec:
  selector:
    app: swiggy
  ports:  # <-- This should be at the same level as "selector"
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort   

