apiVersion: v1
kind: Service
metadata:
  name: swiggy-service  # Changed from my-app-service to swiggy-service
spec:
  selector:
    app: swiggy
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
    nodePort: 32414
    port: 80
    protocol: TCP
    targetPort: 80

