apiVersion: v1
kind: Service
metadata:
  name: swiggy-service  # Changed from my-app-service to swiggy-service
spec:
  selector:
    app: swiggy  # Changed from my-app to swiggy (this must match the labels in Deployment)
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort   

